export const languages = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  no: 'Norsk',
  nl: 'Nederlands',
  id: 'Bahasa Indonesia',
  'zh-CN': '简体中文',
  th: 'ไทย',
};

export type LanguageKey = keyof typeof languages;

type Translation = {
  [key: string]: string;
};

type Translations = {
  [key in LanguageKey]: Translation;
};

export const translations: Translations = {
  en: {
    // Header & Footer
    headerTitle: 'AI Recipe Generator',
    footerText: 'Powered by Gemini API. Happy Cooking!',
    selectLanguageLabel: 'Select language',
    // Ingredient Form
    formTitle: "What's in your fridge?",
    ingredientsLabel: 'List your ingredients or name a dish you would like a recipe for',
    ingredientsPlaceholder: 'e.g., chicken breast, broccoli, garlic, olive oil, lemon',
    mealTypeLabel: 'Meal Type',
    quickMealLabel: 'Prep & Cook in under 30 Minutes',
    dietaryPreferencesLabel: 'Dietary Preferences',
    equipmentLabel: 'Available Equipment',
    generateButton: 'Generate Recipe',
    generateButtonLoading: 'Thinking...',
    // Meal Types
    mealTypeAny: 'Any',
    mealTypeBreakfast: 'Breakfast',
    mealTypeLunch: 'Lunch',
    mealTypeDinner: 'Dinner',
    mealTypeSnack: 'Snack',
    mealTypeDessert: 'Dessert',
    mealTypeSoup: 'Soup',
    // Dietary Options
    dietaryOptionVegetarian: 'Vegetarian',
    dietaryOptionVegan: 'Vegan',
    dietaryOptionGluten_Free: 'Gluten-Free',
    dietaryOptionDairy_Free: 'Dairy-Free',
    // Cooking Methods
    cookingMethodStovetop: 'Stovetop',
    cookingMethodOven: 'Oven',
    cookingMethodMicrowave: 'Microwave',
    cookingMethodGrill: 'Grill',
    cookingMethodCharcoal_BBQ: 'Charcoal BBQ',
    cookingMethodGas_BBQ: 'Gas BBQ',
    cookingMethodAir_Fryer: 'Air Fryer',
    cookingMethodNo_Cook: 'No-Cook',
    // Recipe Display
    tryAnotherButton: 'Try Another',
    saveButton: 'Save Recipe',
    savedButton: 'Saved!',
    recipeSavedTooltip: 'Recipe Saved!',
    watchVideoButton: 'Watch Video',
    generateVideoButton: 'Generate Video',
    generateVideoLoading: 'Crafting your culinary video. This may take a moment. Please scroll down to the recipe or grab a glass of wine. We will catch up with you. The video will open in a new window.',
    prepTimeLabel: 'Prep',
    cookTimeLabel: 'Cook',
    servingsLabel: 'Servings',
    caloriesLabel: 'Calories',
    proteinLabel: 'Protein',
    carbsLabel: 'Carbs',
    fatLabel: 'Fat',
    giLabel: 'GI',
    ingredientsHeader: 'Ingredients',
    instructionsHeader: 'Instructions',
    notesHeader: 'My Notes',
    notesPlaceholder: 'Add your personal notes, adjustments, or serving suggestions here...',
    imagePlaceholder: 'Generating delicious image...',
    emailRecipeButton: 'Email Recipe',
    emailSubjectPrefix: 'Recipe',
    gmailBodyPlaceholder: 'Recipe details have been copied to your clipboard. Please paste them here (Ctrl+V or Cmd+V).',
    recipeNotesLabel: 'Recipe notes',
    rateStarLabel: 'Rate {star} star',
    rateStarsLabel: 'Rate {star} stars',
    medicalDisclaimer: 'NO Information on this App is to be considered medical advice. This App is strictly for entertainment purposes only. The owners will not be held liable in any way',
    downloadImageLabel: 'Download and Share Image',
    // Saved Recipes
    savedRecipesButton: 'Saved Recipes',
    savedRecipesModalTitle: 'My Saved Recipes',
    savedRecipesTitle: 'Saved Recipes',
    searchPlaceholder: 'Search saved recipes...',
    noRecipesFound: 'No matching recipes found.',
    noSavedRecipes: "You haven't saved any recipes yet.",
    searchSavedRecipesLabel: 'Search saved recipes',
    viewRecipeAriaLabel: 'View recipe for {recipeName}',
    deleteRecipeAriaLabel: 'Delete recipe for {recipeName}',
    // Errors
    errorOops: 'Oops!',
    errorIngredients: 'Please enter some ingredients.',
    errorGeneration: 'Sorry, we couldn\'t generate a recipe with those ingredients. Please try again or adjust your ingredients.',
    errorImageGeneration: 'Sorry, we couldn\'t create an image for this recipe.',
    errorVideoGeneration: 'Sorry, we couldn\'t create a video for this recipe.',
    errorSocialPostGeneration: 'Sorry, we couldn\'t generate social media posts. Please try again.',
    // Initial State
    initialStateTitle: 'Your Culinary Creation Awaits',
    initialStateText: 'Enter your ingredients on the left to get started!',
    // Social Post Modal
    socialPostButton: 'Create Social Post',
    socialModalTitle: 'Generate Social Media Post',
    generateSocialPostButton: 'Generate Post',
    generateSocialPostLoading: 'Generating...',
    copyButton: 'Copy',
    copiedButton: 'Copied!',
    generatedPostAriaLabel: 'Generated social media post',
    // Modals
    closeModalLabel: 'Close modal',
    // Video Modal
    videoModalAriaLabel: 'Recipe video',
    videoNotSupported: 'Your browser does not support the video tag.',
    closeVideoLabel: 'Close video',
    downloadAndShare: 'Download and Share',
    downloadVideoLabel: 'Download video',
  },
  es: {
    headerTitle: 'Generador de Recetas con IA',
    footerText: 'Impulsado por Gemini API. ¡Feliz cocina!',
    selectLanguageLabel: 'Seleccionar idioma',
    formTitle: '¿Qué tienes en tu nevera?',
    ingredientsLabel: 'Lista tus ingredientes o nombra un plato para el que te gustaría una receta',
    ingredientsPlaceholder: 'ej., pechuga de pollo, brócoli, ajo, aceite de oliva, limón',
    mealTypeLabel: 'Tipo de Comida',
    quickMealLabel: 'Preparación y cocción en menos de 30 minutos',
    dietaryPreferencesLabel: 'Preferencias Dietéticas',
    equipmentLabel: 'Equipo Disponible',
    generateButton: 'Generar Receta',
    generateButtonLoading: 'Pensando...',
    mealTypeAny: 'Cualquiera',
    mealTypeBreakfast: 'Desayuno',
    mealTypeLunch: 'Almuerzo',
    mealTypeDinner: 'Cena',
    mealTypeSnack: 'Snack',
    mealTypeDessert: 'Postre',
    mealTypeSoup: 'Sopa',
    dietaryOptionVegetarian: 'Vegetariano',
    dietaryOptionVegan: 'Vegano',
    dietaryOptionGluten_Free: 'Sin Gluten',
    dietaryOptionDairy_Free: 'Sin Lácteos',
    cookingMethodStovetop: 'Estufa',
    cookingMethodOven: 'Horno',
    cookingMethodMicrowave: 'Microondas',
    cookingMethodGrill: 'Parrilla',
    cookingMethodCharcoal_BBQ: 'Barbacoa de Carbón',
    cookingMethodGas_BBQ: 'Barbacoa de Gas',
    cookingMethodAir_Fryer: 'Freidora de Aire',
    cookingMethodNo_Cook: 'Sin Cocción',
    tryAnotherButton: 'Probar Otra',
    saveButton: 'Guardar Receta',
    savedButton: '¡Guardada!',
    recipeSavedTooltip: '¡Receta Guardada!',
    watchVideoButton: 'Ver Video',
    generateVideoButton: 'Generar Video',
    generateVideoLoading: 'Creando tu video culinario. Esto puede tomar un momento. Por favor, desplázate hacia la receta o toma una copa de vino. Te alcanzaremos. El video se abrirá en una nueva ventana.',
    prepTimeLabel: 'Prep',
    cookTimeLabel: 'Cocción',
    servingsLabel: 'Porciones',
    caloriesLabel: 'Calorías',
    proteinLabel: 'Proteína',
    carbsLabel: 'Carbs',
    fatLabel: 'Grasa',
    giLabel: 'IG',
    ingredientsHeader: 'Ingredientes',
    instructionsHeader: 'Instrucciones',
    notesHeader: 'Mis Notas',
    notesPlaceholder: 'Añade tus notas personales, ajustes o sugerencias para servir aquí...',
    imagePlaceholder: 'Generando imagen deliciosa...',
    emailRecipeButton: 'Enviar Receta por Email',
    emailSubjectPrefix: 'Receta',
    gmailBodyPlaceholder: 'Los detalles de la receta se han copiado en tu portapapeles. Por favor, pégalos aquí (Ctrl+V o Cmd+V).',
    recipeNotesLabel: 'Notas de la receta',
    rateStarLabel: 'Calificar con {star} estrella',
    rateStarsLabel: 'Calificar con {star} estrellas',
    medicalDisclaimer: 'NINGUNA información en esta aplicación debe ser considerada como consejo médico. Esta aplicación es estrictamente para fines de entretenimiento. Los propietarios no serán responsables de ninguna manera.',
    downloadImageLabel: 'Descargar y Compartir Imagen',
    savedRecipesButton: 'Recetas Guardadas',
    savedRecipesModalTitle: 'Mis Recetas Guardadas',
    savedRecipesTitle: 'Recetas Guardadas',
    searchPlaceholder: 'Buscar recetas guardadas...',
    noRecipesFound: 'No se encontraron recetas coincidentes.',
    noSavedRecipes: 'Aún no has guardado ninguna receta.',
    searchSavedRecipesLabel: 'Buscar recetas guardadas',
    viewRecipeAriaLabel: 'Ver receta de {recipeName}',
    deleteRecipeAriaLabel: 'Eliminar receta de {recipeName}',
    errorOops: '¡Ups!',
    errorIngredients: 'Por favor, introduce algunos ingredientes.',
    errorGeneration: 'Lo sentimos, no pudimos generar una receta con esos ingredientes. Por favor, inténtalo de nuevo o ajusta tus ingredientes.',
    errorImageGeneration: 'Lo sentimos, no pudimos crear una imagen para esta receta.',
    errorVideoGeneration: 'Lo sentimos, no pudimos crear un video para esta receta.',
    errorSocialPostGeneration: 'Lo sentimos, no pudimos generar las publicaciones para redes sociales. Por favor, inténtalo de nuevo.',
    initialStateTitle: 'Tu Creación Culinaria te Espera',
    initialStateText: '¡Introduce tus ingredientes a la izquierda para empezar!',
    socialPostButton: 'Crear Publicación Social',
    socialModalTitle: 'Generar Publicación para Redes Sociales',
    generateSocialPostButton: 'Generar Publicación',
    generateSocialPostLoading: 'Generando...',
    copyButton: 'Copiar',
    copiedButton: '¡Copiado!',
    generatedPostAriaLabel: 'Publicación de redes sociales generada',
    closeModalLabel: 'Cerrar modal',
    videoModalAriaLabel: 'Video de receta',
    videoNotSupported: 'Tu navegador no soporta la etiqueta de video.',
    closeVideoLabel: 'Cerrar video',
    downloadAndShare: 'Descargar y Compartir',
    downloadVideoLabel: 'Descargar video',
  },
  fr: {
    headerTitle: 'Générateur de Recettes IA',
    footerText: 'Propulsé par Gemini API. Bonne cuisine !',
    selectLanguageLabel: 'Sélectionner la langue',
    formTitle: 'Qu\'y a-t-il dans votre frigo ?',
    ingredientsLabel: 'Listez vos ingrédients ou nommez un plat pour lequel vous aimeriez une recette',
    ingredientsPlaceholder: 'ex: blanc de poulet, brocoli, ail, huile d\'olive, citron',
    mealTypeLabel: 'Type de Repas',
    quickMealLabel: 'Préparation et cuisson en moins de 30 minutes',
    dietaryPreferencesLabel: 'Préférences Alimentaires',
    equipmentLabel: 'Équipement Disponible',
    generateButton: 'Générer la Recette',
    generateButtonLoading: 'Réflexion...',
    mealTypeAny: 'Tous',
    mealTypeBreakfast: 'Petit-déjeuner',
    mealTypeLunch: 'Déjeuner',
    mealTypeDinner: 'Dîner',
    mealTypeSnack: 'En-cas',
    mealTypeDessert: 'Dessert',
    mealTypeSoup: 'Soupe',
    dietaryOptionVegetarian: 'Végétarien',
    dietaryOptionVegan: 'Végétalien',
    dietaryOptionGluten_Free: 'Sans Gluten',
    dietaryOptionDairy_Free: 'Sans Produits Laitiers',
    cookingMethodStovetop: 'Cuisinière',
    cookingMethodOven: 'Four',
    cookingMethodMicrowave: 'Micro-ondes',
    cookingMethodGrill: 'Gril',
    cookingMethodCharcoal_BBQ: 'BBQ au Charbon',
    cookingMethodGas_BBQ: 'BBQ au Gaz',
    cookingMethodAir_Fryer: 'Friteuse à Air',
    cookingMethodNo_Cook: 'Sans Cuisson',
    tryAnotherButton: 'Essayer une autre',
    saveButton: 'Sauvegarder',
    savedButton: 'Enregistrée !',
    recipeSavedTooltip: 'Recette Enregistrée !',
    watchVideoButton: 'Regarder la Vidéo',
    generateVideoButton: 'Générer la Vidéo',
    generateVideoLoading: 'Création de votre vidéo culinaire. Cela peut prendre un moment. Veuillez faire défiler jusqu\'à la recette ou prendre un verre de vin. Nous vous rattraperons. La vidéo s\'ouvrira dans une nouvelle fenêtre.',
    prepTimeLabel: 'Prép',
    cookTimeLabel: 'Cuisson',
    servingsLabel: 'Portions',
    caloriesLabel: 'Calories',
    proteinLabel: 'Protéines',
    carbsLabel: 'Glucides',
    fatLabel: 'Lipides',
    giLabel: 'IG',
    ingredientsHeader: 'Ingrédients',
    instructionsHeader: 'Instructions',
    notesHeader: 'Mes Notes',
    notesPlaceholder: 'Ajoutez vos notes personnelles, ajustements ou suggestions de service ici...',
    imagePlaceholder: 'Génération d\'une image délicieuse...',
    emailRecipeButton: 'Envoyer la Recette par E-mail',
    emailSubjectPrefix: 'Recette',
    gmailBodyPlaceholder: 'Les détails de la recette ont été copiés dans votre presse-papiers. Veuillez les coller ici (Ctrl+V ou Cmd+V).',
    recipeNotesLabel: 'Notes de recette',
    rateStarLabel: 'Évaluer {star} étoile',
    rateStarsLabel: 'Évaluer {star} étoiles',
    medicalDisclaimer: 'AUCUNE information sur cette application ne doit être considérée comme un avis médical. Cette application est uniquement à des fins de divertissement. Les propriétaires ne seront en aucun cas tenus responsables.',
    downloadImageLabel: 'Télécharger et Partager l\'Image',
    savedRecipesButton: 'Recettes Enregistrées',
    savedRecipesModalTitle: 'Mes Recettes Enregistrées',
    savedRecipesTitle: 'Recettes Enregistrées',
    searchPlaceholder: 'Rechercher des recettes...',
    noRecipesFound: 'Aucune recette correspondante trouvée.',
    noSavedRecipes: "Vous n'avez pas encore enregistré de recettes.",
    searchSavedRecipesLabel: 'Rechercher dans les recettes enregistrées',
    viewRecipeAriaLabel: 'Voir la recette pour {recipeName}',
    deleteRecipeAriaLabel: 'Supprimer la recette pour {recipeName}',
    errorOops: 'Oups !',
    errorIngredients: 'Veuillez entrer quelques ingrédients.',
    errorGeneration: 'Désolé, nous n\'avons pas pu générer de recette avec ces ingrédients. Veuillez réessayer ou ajuster vos ingrédients.',
    errorImageGeneration: 'Désolé, nous n\'avons pas pu créer d\'image pour cette recette.',
    errorVideoGeneration: 'Désolé, nous n\'avons pas pu créer de vidéo pour cette recette.',
    errorSocialPostGeneration: 'Désolé, nous n\'avons pas pu générer les publications pour les réseaux sociaux. Veuillez réessayer.',
    initialStateTitle: 'Votre Création Culinaire vous Attend',
    initialStateText: 'Entrez vos ingrédients à gauche pour commencer !',
    socialPostButton: 'Créer un Post Social',
    socialModalTitle: 'Générer un Post pour les Réseaux Sociaux',
    generateSocialPostButton: 'Générer le Post',
    generateSocialPostLoading: 'Génération...',
    copyButton: 'Copier',
    copiedButton: 'Copié !',
    generatedPostAriaLabel: 'Post de réseau social généré',
    closeModalLabel: 'Fermer la modale',
    videoModalAriaLabel: 'Vidéo de recette',
    videoNotSupported: 'Votre navigateur ne prend pas en charge la balise vidéo.',
    closeVideoLabel: 'Fermer la vidéo',
    downloadAndShare: 'Télécharger et Partager',
    downloadVideoLabel: 'Télécharger la vidéo',
  },
  de: {
    headerTitle: 'KI-Rezeptgenerator',
    footerText: 'Unterstützt von Gemini API. Viel Spaß beim Kochen!',
    selectLanguageLabel: 'Sprache auswählen',
    formTitle: 'Was ist in Ihrem Kühlschrank?',
    ingredientsLabel: 'Listen Sie Ihre Zutaten auf oder nennen Sie ein Gericht, für das Sie ein Rezept möchten',
    ingredientsPlaceholder: 'z.B. Hähnchenbrust, Brokkoli, Knoblauch, Olivenöl, Zitrone',
    mealTypeLabel: 'Mahlzeit-Typ',
    quickMealLabel: 'Zubereitung & Kochen in unter 30 Minuten',
    dietaryPreferencesLabel: 'Ernährungspräferenzen',
    equipmentLabel: 'Verfügbare Ausstattung',
    generateButton: 'Rezept generieren',
    generateButtonLoading: 'Denken...',
    mealTypeAny: 'Beliebig',
    mealTypeBreakfast: 'Frühstück',
    mealTypeLunch: 'Mittagessen',
    mealTypeDinner: 'Abendessen',
    mealTypeSnack: 'Snack',
    mealTypeDessert: 'Dessert',
    mealTypeSoup: 'Suppe',
    dietaryOptionVegetarian: 'Vegetarisch',
    dietaryOptionVegan: 'Vegan',
    dietaryOptionGluten_Free: 'Glutenfrei',
    dietaryOptionDairy_Free: 'Milchfrei',
    cookingMethodStovetop: 'Herd',
    cookingMethodOven: 'Ofen',
    cookingMethodMicrowave: 'Mikrowelle',
    cookingMethodGrill: 'Grill',
    cookingMethodCharcoal_BBQ: 'Holzkohlegrill',
    cookingMethodGas_BBQ: 'Gasgrill',
    cookingMethodAir_Fryer: 'Heißluftfritteuse',
    cookingMethodNo_Cook: 'Ohne Kochen',
    tryAnotherButton: 'Ein anderes versuchen',
    saveButton: 'Rezept speichern',
    savedButton: 'Gespeichert!',
    recipeSavedTooltip: 'Rezept gespeichert!',
    watchVideoButton: 'Video ansehen',
    generateVideoButton: 'Video generieren',
    generateVideoLoading: 'Ihr kulinarisches Video wird erstellt. Dies kann einen Moment dauern. Bitte scrollen Sie zum Rezept oder holen Sie sich ein Glas Wein. Wir melden uns bei Ihnen. Das Video wird in einem neuen Fenster geöffnet.',
    prepTimeLabel: 'Vorb.',
    cookTimeLabel: 'Kochz.',
    servingsLabel: 'Portionen',
    caloriesLabel: 'Kalorien',
    proteinLabel: 'Protein',
    carbsLabel: 'Kohlenh.',
    fatLabel: 'Fett',
    giLabel: 'GI',
    ingredientsHeader: 'Zutaten',
    instructionsHeader: 'Anweisungen',
    notesHeader: 'Meine Notizen',
    notesPlaceholder: 'Fügen Sie hier Ihre persönlichen Notizen, Anpassungen oder Serviervorschläge hinzu...',
    imagePlaceholder: 'Leckeres Bild wird generiert...',
    emailRecipeButton: 'Rezept per E-Mail senden',
    emailSubjectPrefix: 'Rezept',
    gmailBodyPlaceholder: 'Die Rezeptdetails wurden in Ihre Zwischenablage kopiert. Bitte fügen Sie sie hier ein (Strg+V oder Cmd+V).',
    recipeNotesLabel: 'Rezeptnotizen',
    rateStarLabel: '{star} Stern bewerten',
    rateStarsLabel: '{star} Sterne bewerten',
    medicalDisclaimer: 'KEINE Informationen in dieser App sind als medizinischer Rat zu betrachten. Diese App dient ausschließlich zu Unterhaltungszwecken. Die Eigentümer haften in keiner Weise.',
    downloadImageLabel: 'Bild herunterladen und teilen',
    savedRecipesButton: 'Gespeicherte Rezepte',
    savedRecipesModalTitle: 'Meine Gespeicherten Rezepte',
    savedRecipesTitle: 'Gespeicherte Rezepte',
    searchPlaceholder: 'Gespeicherte Rezepte suchen...',
    noRecipesFound: 'Keine passenden Rezepte gefunden.',
    noSavedRecipes: 'Sie haben noch keine Rezepte gespeichert.',
    searchSavedRecipesLabel: 'Gespeicherte Rezepte suchen',
    viewRecipeAriaLabel: 'Rezept für {recipeName} ansehen',
    deleteRecipeAriaLabel: 'Rezept für {recipeName} löschen',
    errorOops: 'Hoppla!',
    errorIngredients: 'Bitte geben Sie einige Zutaten ein.',
    errorGeneration: 'Entschuldigung, wir konnten mit diesen Zutaten kein Rezept erstellen. Bitte versuchen Sie es erneut oder passen Sie Ihre Zutaten an.',
    errorImageGeneration: 'Entschuldigung, wir konnten kein Bild für dieses Rezept erstellen.',
    errorVideoGeneration: 'Entschuldigung, wir konnten kein Video für dieses Rezept erstellen.',
    errorSocialPostGeneration: 'Entschuldigung, wir konnten keine Social-Media-Beiträge generieren. Bitte versuchen Sie es erneut.',
    initialStateTitle: 'Ihre kulinarische Kreation erwartet Sie',
    initialStateText: 'Geben Sie links Ihre Zutaten ein, um loszulegen!',
    socialPostButton: 'Social-Media-Beitrag erstellen',
    socialModalTitle: 'Social-Media-Beitrag generieren',
    generateSocialPostButton: 'Beitrag generieren',
    generateSocialPostLoading: 'Wird generiert...',
    copyButton: 'Kopieren',
    copiedButton: 'Kopiert!',
    generatedPostAriaLabel: 'Generierter Social-Media-Beitrag',
    closeModalLabel: 'Modal schließen',
    videoModalAriaLabel: 'Rezeptvideo',
    videoNotSupported: 'Ihr Browser unterstützt das Video-Tag nicht.',
    closeVideoLabel: 'Video schließen',
    downloadAndShare: 'Herunterladen und Teilen',
    downloadVideoLabel: 'Video herunterladen',
  },
  it: {
    headerTitle: 'Generatore di Ricette AI',
    footerText: 'Realizzato con Gemini API. Buona cucina!',
    selectLanguageLabel: 'Seleziona la lingua',
    formTitle: 'Cosa c\'è nel tuo frigo?',
    ingredientsLabel: 'Elenca i tuoi ingredienti o nomina un piatto per cui vorresti una ricetta',
    ingredientsPlaceholder: 'es. petto di pollo, broccoli, aglio, olio d\'oliva, limone',
    mealTypeLabel: 'Tipo di Pasto',
    quickMealLabel: 'Preparazione e cottura in meno di 30 minuti',
    dietaryPreferencesLabel: 'Preferenze Alimentari',
    equipmentLabel: 'Attrezzatura Disponibile',
    generateButton: 'Genera Ricetta',
    generateButtonLoading: 'Sto pensando...',
    mealTypeAny: 'Qualsiasi',
    mealTypeBreakfast: 'Colazione',
    mealTypeLunch: 'Pranzo',
    mealTypeDinner: 'Cena',
    mealTypeSnack: 'Spuntino',
    mealTypeDessert: 'Dessert',
    mealTypeSoup: 'Zuppa',
    dietaryOptionVegetarian: 'Vegetariano',
    dietaryOptionVegan: 'Vegano',
    dietaryOptionGluten_Free: 'Senza Glutine',
    dietaryOptionDairy_Free: 'Senza Latticini',
    cookingMethodStovetop: 'Fornello',
    cookingMethodOven: 'Forno',
    cookingMethodMicrowave: 'Microonde',
    cookingMethodGrill: 'Griglia',
    cookingMethodCharcoal_BBQ: 'BBQ a Carbone',
    cookingMethodGas_BBQ: 'BBQ a Gas',
    cookingMethodAir_Fryer: 'Friggitrice ad Aria',
    cookingMethodNo_Cook: 'Senza Cottura',
    tryAnotherButton: 'Provane un\'altra',
    saveButton: 'Salva Ricetta',
    savedButton: 'Salvata!',
    recipeSavedTooltip: 'Ricetta Salvata!',
    watchVideoButton: 'Guarda il Video',
    generateVideoButton: 'Genera Video',
    generateVideoLoading: 'Creazione del tuo video culinario. Potrebbe volerci un momento. Scorri verso la ricetta o prendi un bicchiere di vino. Ti raggiungeremo. Il video si aprirà in una nuova finestra.',
    prepTimeLabel: 'Prep',
    cookTimeLabel: 'Cottura',
    servingsLabel: 'Porzioni',
    caloriesLabel: 'Calorie',
    proteinLabel: 'Proteine',
    carbsLabel: 'Carboid.',
    fatLabel: 'Grassi',
    giLabel: 'IG',
    ingredientsHeader: 'Ingredienti',
    instructionsHeader: 'Istruzioni',
    notesHeader: 'Le mie Note',
    notesPlaceholder: 'Aggiungi qui le tue note personali, modifiche o suggerimenti di servizio...',
    imagePlaceholder: 'Generazione di un\'immagine deliziosa...',
    emailRecipeButton: 'Invia Ricetta via Email',
    emailSubjectPrefix: 'Ricetta',
    gmailBodyPlaceholder: 'I dettagli della ricetta sono stati copiati negli appunti. Si prega di incollarli qui (Ctrl+V o Cmd+V).',
    recipeNotesLabel: 'Note sulla ricetta',
    rateStarLabel: 'Valuta {star} stella',
    rateStarsLabel: 'Valuta {star} stelle',
    medicalDisclaimer: 'NESSUNA informazione su questa App è da considerarsi un consiglio medico. Questa App è esclusivamente a scopo di intrattenimento. I proprietari non saranno ritenuti responsabili in alcun modo.',
    downloadImageLabel: 'Scarica e Condividi Immagine',
    savedRecipesButton: 'Ricette Salvate',
    savedRecipesModalTitle: 'Le mie Ricette Salvate',
    savedRecipesTitle: 'Ricette Salvate',
    searchPlaceholder: 'Cerca ricette salvate...',
    noRecipesFound: 'Nessuna ricetta corrispondente trovata.',
    noSavedRecipes: 'Non hai ancora salvato nessuna ricetta.',
    searchSavedRecipesLabel: 'Cerca ricette salvate',
    viewRecipeAriaLabel: 'Visualizza la ricetta per {recipeName}',
    deleteRecipeAriaLabel: 'Elimina la ricetta per {recipeName}',
    errorOops: 'Ops!',
    errorIngredients: 'Per favore, inserisci alcuni ingredienti.',
    errorGeneration: 'Spiacenti, non siamo riusciti a generare una ricetta con questi ingredienti. Riprova o modifica i tuoi ingredienti.',
    errorImageGeneration: 'Spiacenti, non siamo riusciti a creare un\'immagine per questa ricetta.',
    errorVideoGeneration: 'Spiacenti, non siamo riusciti a creare un video per questa ricetta.',
    errorSocialPostGeneration: 'Spiacenti, non siamo riusciti a generare i post per i social media. Riprova.',
    initialStateTitle: 'La tua Creazione Culinaria Attende',
    initialStateText: 'Inserisci i tuoi ingredienti a sinistra per iniziare!',
    socialPostButton: 'Crea Post Social',
    socialModalTitle: 'Genera Post per Social Media',
    generateSocialPostButton: 'Genera Post',
    generateSocialPostLoading: 'Sto generando...',
    copyButton: 'Copia',
    copiedButton: 'Copiato!',
    generatedPostAriaLabel: 'Post per social media generato',
    closeModalLabel: 'Chiudi modale',
    videoModalAriaLabel: 'Video della ricetta',
    videoNotSupported: 'Il tuo browser non supporta il tag video.',
    closeVideoLabel: 'Chiudi video',
    downloadAndShare: 'Scarica e Condividi',
    downloadVideoLabel: 'Scarica video',
  },
  pt: {
    headerTitle: 'Gerador de Receitas com IA',
    footerText: 'Desenvolvido com Gemini API. Bom cozinhado!',
    selectLanguageLabel: 'Selecione o idioma',
    formTitle: 'O que há na sua geladeira?',
    ingredientsLabel: 'Liste seus ingredientes ou diga o nome de um prato para o qual você gostaria de uma receita',
    ingredientsPlaceholder: 'ex: peito de frango, brócolis, alho, azeite, limão',
    mealTypeLabel: 'Tipo de Refeição',
    quickMealLabel: 'Preparar e cozinhar em menos de 30 minutos',
    dietaryPreferencesLabel: 'Preferências Alimentares',
    equipmentLabel: 'Equipamento Disponível',
    generateButton: 'Gerar Receita',
    generateButtonLoading: 'Pensando...',
    mealTypeAny: 'Qualquer',
    mealTypeBreakfast: 'Café da Manhã',
    mealTypeLunch: 'Almoço',
    mealTypeDinner: 'Jantar',
    mealTypeSnack: 'Lanche',
    mealTypeDessert: 'Sobremesa',
    mealTypeSoup: 'Sopa',
    dietaryOptionVegetarian: 'Vegetariano',
    dietaryOptionVegan: 'Vegano',
    dietaryOptionGluten_Free: 'Sem Glúten',
    dietaryOptionDairy_Free: 'Sem Laticínios',
    cookingMethodStovetop: 'Fogão',
    cookingMethodOven: 'Forno',
    cookingMethodMicrowave: 'Micro-ondas',
    cookingMethodGrill: 'Grelha',
    cookingMethodCharcoal_BBQ: 'Churrasqueira a Carvão',
    cookingMethodGas_BBQ: 'Churrasqueira a Gás',
    cookingMethodAir_Fryer: 'Fritadeira de Ar',
    cookingMethodNo_Cook: 'Sem Cozimento',
    tryAnotherButton: 'Tentar Outra',
    saveButton: 'Salvar Receita',
    savedButton: 'Salva!',
    recipeSavedTooltip: 'Receita Salva!',
    watchVideoButton: 'Assistir Vídeo',
    generateVideoButton: 'Gerar Vídeo',
    generateVideoLoading: 'Criando seu vídeo culinário. Isso pode levar um momento. Role para baixo até a receita ou pegue uma taça de vinho. Nós o alcançaremos. O vídeo será aberto em uma nova janela.',
    prepTimeLabel: 'Prep',
    cookTimeLabel: 'Coz.',
    servingsLabel: 'Porções',
    caloriesLabel: 'Calorias',
    proteinLabel: 'Proteína',
    carbsLabel: 'Carbs',
    fatLabel: 'Gordura',
    giLabel: 'IG',
    ingredientsHeader: 'Ingredientes',
    instructionsHeader: 'Instruções',
    notesHeader: 'Minhas Notas',
    notesPlaceholder: 'Adicione suas notas pessoais, ajustes ou sugestões de serviço aqui...',
    imagePlaceholder: 'Gerando imagem deliciosa...',
    emailRecipeButton: 'Enviar Receita por E-mail',
    emailSubjectPrefix: 'Receita',
    gmailBodyPlaceholder: 'Os detalhes da receita foram copiados para a área de transferência. Cole-os aqui (Ctrl+V ou Cmd+V).',
    recipeNotesLabel: 'Notas da receita',
    rateStarLabel: 'Avalie com {star} estrela',
    rateStarsLabel: 'Avalie com {star} estrelas',
    medicalDisclaimer: 'NENHUMA informação neste aplicativo deve ser considerada como aconselhamento médico. Este aplicativo é estritamente para fins de entretenimento. Os proprietários não serão responsabilizados de forma alguma.',
    downloadImageLabel: 'Baixar e Compartilhar Imagem',
    savedRecipesButton: 'Receitas Salvas',
    savedRecipesModalTitle: 'Minhas Receitas Salvas',
    savedRecipesTitle: 'Receitas Salvas',
    searchPlaceholder: 'Pesquisar receitas salvas...',
    noRecipesFound: 'Nenhuma receita encontrada.',
    noSavedRecipes: 'Você ainda não salvou nenhuma receita.',
    searchSavedRecipesLabel: 'Pesquisar receitas salvas',
    viewRecipeAriaLabel: 'Ver receita de {recipeName}',
    deleteRecipeAriaLabel: 'Excluir receita de {recipeName}',
    errorOops: 'Opa!',
    errorIngredients: 'Por favor, insira alguns ingredientes.',
    errorGeneration: 'Desculpe, não conseguimos gerar uma receita com esses ingredientes. Tente novamente ou ajuste seus ingredientes.',
    errorImageGeneration: 'Desculpe, não conseguimos criar uma imagem para esta receita.',
    errorVideoGeneration: 'Desculpe, não conseguimos criar um vídeo para esta receita.',
    errorSocialPostGeneration: 'Desculpe, não conseguimos gerar as postagens para as redes sociais. Por favor, tente novamente.',
    initialStateTitle: 'Sua Criação Culinária Aguarda',
    initialStateText: 'Insira seus ingredientes à esquerda para começar!',
    socialPostButton: 'Criar Post Social',
    socialModalTitle: 'Gerar Post para Redes Sociais',
    generateSocialPostButton: 'Gerar Post',
    generateSocialPostLoading: 'Gerando...',
    copyButton: 'Copiar',
    copiedButton: 'Copiado!',
    generatedPostAriaLabel: 'Postagem de rede social gerada',
    closeModalLabel: 'Fechar modal',
    videoModalAriaLabel: 'Vídeo da receita',
    videoNotSupported: 'Seu navegador não suporta a tag de vídeo.',
    closeVideoLabel: 'Fechar vídeo',
    downloadAndShare: 'Baixar e Compartilhar',
    downloadVideoLabel: 'Baixar vídeo',
  },
  no: {
    headerTitle: 'AI Oppskriftsgenerator',
    footerText: 'Drevet av Gemini API. God matlaging!',
    selectLanguageLabel: 'Velg språk',
    formTitle: 'Hva har du i kjøleskapet?',
    ingredientsLabel: 'List opp ingrediensene dine eller navngi en rett du ønsker en oppskrift på',
    ingredientsPlaceholder: 'f.eks. kyllingbryst, brokkoli, hvitløk, olivenolje, sitron',
    mealTypeLabel: 'Måltidstype',
    quickMealLabel: 'Forberedelse og matlaging på under 30 minutter',
    dietaryPreferencesLabel: 'Kostholdspreferanser',
    equipmentLabel: 'Tilgjengelig Utstyr',
    generateButton: 'Generer Oppskrift',
    generateButtonLoading: 'Tenker...',
    mealTypeAny: 'Alle',
    mealTypeBreakfast: 'Frokost',
    mealTypeLunch: 'Lunsj',
    mealTypeDinner: 'Middag',
    mealTypeSnack: 'Snack',
    mealTypeDessert: 'Dessert',
    mealTypeSoup: 'Suppe',
    dietaryOptionVegetarian: 'Vegetarisk',
    dietaryOptionVegan: 'Vegansk',
    dietaryOptionGluten_Free: 'Glutenfri',
    dietaryOptionDairy_Free: 'Melkefri',
    cookingMethodStovetop: 'Komfyr',
    cookingMethodOven: 'Ovn',
    cookingMethodMicrowave: 'Mikrobølgeovn',
    cookingMethodGrill: 'Grill',
    cookingMethodCharcoal_BBQ: 'Kullgrill',
    cookingMethodGas_BBQ: 'Gassgrill',
    cookingMethodAir_Fryer: 'Airfryer',
    cookingMethodNo_Cook: 'Uten Koking',
    tryAnotherButton: 'Prøv en annen',
    saveButton: 'Lagre Oppskrift',
    savedButton: 'Lagret!',
    recipeSavedTooltip: 'Oppskrift Lagret!',
    watchVideoButton: 'Se Video',
    generateVideoButton: 'Generer Video',
    generateVideoLoading: 'Lager din kulinariske video. Dette kan ta et øyeblikk. Vennligst rull ned til oppskriften eller ta et glass vin. Vi tar deg igjen. Videoen åpnes i et nytt vindu.',
    prepTimeLabel: 'Forb',
    cookTimeLabel: 'Tilber.',
    servingsLabel: 'Porsjoner',
    caloriesLabel: 'Kalorier',
    proteinLabel: 'Protein',
    carbsLabel: 'Karbo',
    fatLabel: 'Fett',
    giLabel: 'GI',
    ingredientsHeader: 'Ingredienser',
    instructionsHeader: 'Instruksjoner',
    notesHeader: 'Mine Notater',
    notesPlaceholder: 'Legg til dine personlige notater, justeringer eller serveringsforslag her...',
    imagePlaceholder: 'Genererer deilig bilde...',
    emailRecipeButton: 'Send Oppskrift på E-post',
    emailSubjectPrefix: 'Oppskrift',
    gmailBodyPlaceholder: 'Oppskriftsdetaljene er kopiert til utklippstavlen. Lim dem inn her (Ctrl+V eller Cmd+V).',
    recipeNotesLabel: 'Oppskriftsnotater',
    rateStarLabel: 'Vurder {star} stjerne',
    rateStarsLabel: 'Vurder {star} stjerner',
    medicalDisclaimer: 'INGEN informasjon på denne appen skal betraktes som medisinsk rådgivning. Denne appen er kun for underholdningsformål. Eierne vil ikke bli holdt ansvarlige på noen måte.',
    downloadImageLabel: 'Last ned og Del Bilde',
    savedRecipesButton: 'Lagrede Oppskrifter',
    savedRecipesModalTitle: 'Mine Lagrede Oppskrifter',
    savedRecipesTitle: 'Lagrede Oppskrifter',
    searchPlaceholder: 'Søk i lagrede oppskrifter...',
    noRecipesFound: 'Ingen matchende oppskrifter funnet.',
    noSavedRecipes: 'Du har ikke lagret noen oppskrifter ennå.',
    searchSavedRecipesLabel: 'Søk i lagrede oppskrifter',
    viewRecipeAriaLabel: 'Se oppskrift for {recipeName}',
    deleteRecipeAriaLabel: 'Slett oppskrift for {recipeName}',
    errorOops: 'Oisann!',
    errorIngredients: 'Vennligst skriv inn noen ingredienser.',
    errorGeneration: 'Beklager, vi kunne ikke generere en oppskrift med disse ingrediensene. Prøv igjen eller juster ingrediensene dine.',
    errorImageGeneration: 'Beklager, vi kunne ikke lage et bilde for denne oppskriften.',
    errorVideoGeneration: 'Beklager, vi kunne ikke lage en video for denne oppskriften.',
    errorSocialPostGeneration: 'Beklager, vi kunne ikke generere innlegg for sosiale medier. Vennligst prøv igjen.',
    initialStateTitle: 'Din Kulinariske Kreasjon Venter',
    initialStateText: 'Skriv inn ingrediensene dine til venstre for å komme i gang!',
    socialPostButton: 'Lag Sosialt Innlegg',
    socialModalTitle: 'Generer Innlegg for Sosiale Medier',
    generateSocialPostButton: 'Generer Innlegg',
    generateSocialPostLoading: 'Genererer...',
    copyButton: 'Kopier',
    copiedButton: 'Kopiert!',
    generatedPostAriaLabel: 'Generert innlegg for sosiale medier',
    closeModalLabel: 'Lukk modal',
    videoModalAriaLabel: 'Oppskriftsvideo',
    videoNotSupported: 'Nettleseren din støtter ikke video-taggen.',
    closeVideoLabel: 'Lukk video',
    downloadAndShare: 'Last ned og Del',
    downloadVideoLabel: 'Last ned video',
  },
  nl: {
    headerTitle: 'AI Receptengenerator',
    footerText: 'Mogelijk gemaakt door de Gemini API. Veel kookplezier!',
    selectLanguageLabel: 'Selecteer taal',
    formTitle: 'Wat ligt er in je koelkast?',
    ingredientsLabel: 'Jouw ingrediënten of noem een gerecht waar je een recept voor wilt',
    ingredientsPlaceholder: 'bijv. kipfilet, broccoli, knoflook, olijfolie, citroen',
    mealTypeLabel: 'Type maaltijd',
    quickMealLabel: 'Voorbereiden & koken in minder dan 30 minuten',
    dietaryPreferencesLabel: 'Dieetvoorkeuren',
    equipmentLabel: 'Beschikbare apparatuur',
    generateButton: 'Genereer Recept',
    generateButtonLoading: 'Bezig met denken...',
    mealTypeAny: 'Alle',
    mealTypeBreakfast: 'Ontbijt',
    mealTypeLunch: 'Lunch',
    mealTypeDinner: 'Diner',
    mealTypeSnack: 'Snack',
    mealTypeDessert: 'Dessert',
    mealTypeSoup: 'Soep',
    dietaryOptionVegetarian: 'Vegetarisch',
    dietaryOptionVegan: 'Veganistisch',
    dietaryOptionGluten_Free: 'Glutenvrij',
    dietaryOptionDairy_Free: 'Zonder zuivel',
    cookingMethodStovetop: 'Fornuis',
    cookingMethodOven: 'Oven',
    cookingMethodMicrowave: 'Magnetron',
    cookingMethodGrill: 'Grill',
    cookingMethodCharcoal_BBQ: 'Houtskool BBQ',
    cookingMethodGas_BBQ: 'Gas BBQ',
    cookingMethodAir_Fryer: 'Airfryer',
    cookingMethodNo_Cook: 'Zonder koken',
    tryAnotherButton: 'Probeer een Ander',
    saveButton: 'Sla Recept Op',
    savedButton: 'Opgeslagen!',
    recipeSavedTooltip: 'Recept opgeslagen!',
    watchVideoButton: 'Bekijk Video',
    generateVideoButton: 'Genereer Video',
    generateVideoLoading: 'Je culinaire video wordt gemaakt. Dit kan even duren. Scroll naar beneden naar het recept of pak een glas wijn. We halen je in. De video wordt in een nieuw venster geopend.',
    prepTimeLabel: 'Voorb.',
    cookTimeLabel: 'Kooktijd',
    servingsLabel: 'Porties',
    caloriesLabel: 'Calorieën',
    proteinLabel: 'Eiwit',
    carbsLabel: 'Koolhydr.',
    fatLabel: 'Vet',
    giLabel: 'GI',
    ingredientsHeader: 'Ingrediënten',
    instructionsHeader: 'Instructies',
    notesHeader: 'Mijn Notities',
    notesPlaceholder: 'Voeg hier je persoonlijke notities, aanpassingen of serveertips toe...',
    imagePlaceholder: 'Heerlijke afbeelding genereren...',
    emailRecipeButton: 'Mail Recept',
    emailSubjectPrefix: 'Recept',
    gmailBodyPlaceholder: 'De receptdetails zijn naar je klembord gekopieerd. Plak ze hier (Ctrl+V of Cmd+V).',
    recipeNotesLabel: 'Receptnotities',
    rateStarLabel: 'Beoordeel {star} ster',
    rateStarsLabel: 'Beoordeel {star} sterren',
    medicalDisclaimer: 'GEEN informatie op deze app mag worden beschouwd als medisch advies. Deze app is uitsluitend bedoeld voor amusementsdoeleinden. De eigenaren kunnen op geen enkele wijze aansprakelijk worden gesteld.',
    downloadImageLabel: 'Download en Deel Afbeelding',
    savedRecipesButton: 'Opgeslagen Recepten',
    savedRecipesModalTitle: 'Mijn Opgeslagen Recepten',
    savedRecipesTitle: 'Opgeslagen Recepten',
    searchPlaceholder: 'Zoek opgeslagen recepten...',
    noRecipesFound: 'Geen overeenkomende recepten gevonden.',
    noSavedRecipes: 'Je hebt nog geen recepten opgeslagen.',
    searchSavedRecipesLabel: 'Zoek opgeslagen recepten',
    viewRecipeAriaLabel: 'Bekijk recept voor {recipeName}',
    deleteRecipeAriaLabel: 'Verwijder recept voor {recipeName}',
    errorOops: 'Oeps!',
    errorIngredients: 'Voer alstublieft wat ingrediënten in.',
    errorGeneration: 'Sorry, we konden geen recept genereren met deze ingrediënten. Probeer het alstublieft opnieuw of pas uw ingrediënten aan.',
    errorImageGeneration: 'Sorry, we konden geen afbeelding voor dit recept maken.',
    errorVideoGeneration: 'Sorry, we konden geen video voor dit recept maken.',
    errorSocialPostGeneration: 'Sorry, we konden geen social media posts genereren. Probeer het opnieuw.',
    initialStateTitle: 'Jouw culinaire creatie wacht',
    initialStateText: 'Voer links je ingrediënten in om te beginnen!',
    socialPostButton: 'Maak Social Post',
    socialModalTitle: 'Genereer Social Media Post',
    generateSocialPostButton: 'Genereer Post',
    generateSocialPostLoading: 'Bezig met genereren...',
    copyButton: 'Kopieer',
    copiedButton: 'Gekopieerd!',
    generatedPostAriaLabel: 'Gegenereerde social media post',
    closeModalLabel: 'Sluit modal',
    videoModalAriaLabel: 'Receptvideo',
    videoNotSupported: 'Uw browser ondersteunt de videotag niet.',
    closeVideoLabel: 'Sluit video',
    downloadAndShare: 'Download en Deel',
    downloadVideoLabel: 'Download video',
  },
  id: {
    headerTitle: 'Generator Resep AI',
    footerText: 'Didukung oleh Gemini API. Selamat memasak!',
    selectLanguageLabel: 'Pilih bahasa',
    formTitle: 'Apa yang ada di kulkas Anda?',
    ingredientsLabel: 'Daftar bahan-bahan Anda atau sebutkan nama masakan yang resepnya Anda inginkan',
    ingredientsPlaceholder: 'contoh: dada ayam, brokoli, bawang putih, minyak zaitun, lemon',
    mealTypeLabel: 'Jenis Makanan',
    quickMealLabel: 'Persiapan & Masak dalam waktu kurang dari 30 Menit',
    dietaryPreferencesLabel: 'Preferensi Diet',
    equipmentLabel: 'Peralatan yang Tersedia',
    generateButton: 'Hasilkan Resep',
    generateButtonLoading: 'Berpikir...',
    mealTypeAny: 'Apa saja',
    mealTypeBreakfast: 'Sarapan',
    mealTypeLunch: 'Makan Siang',
    mealTypeDinner: 'Makan Malam',
    mealTypeSnack: 'Camilan',
    mealTypeDessert: 'Hidangan Penutup',
    mealTypeSoup: 'Sup',
    dietaryOptionVegetarian: 'Vegetarian',
    dietaryOptionVegan: 'Vegan',
    dietaryOptionGluten_Free: 'Bebas Gluten',
    dietaryOptionDairy_Free: 'Bebas Susu',
    cookingMethodStovetop: 'Kompor',
    cookingMethodOven: 'Oven',
    cookingMethodMicrowave: 'Microwave',
    cookingMethodGrill: 'Panggangan',
    cookingMethodCharcoal_BBQ: 'BBQ Arang',
    cookingMethodGas_BBQ: 'BBQ Gas',
    cookingMethodAir_Fryer: 'Penggoreng Udara',
    cookingMethodNo_Cook: 'Tanpa Memasak',
    tryAnotherButton: 'Coba yang Lain',
    saveButton: 'Simpan Resep',
    savedButton: 'Tersimpan!',
    recipeSavedTooltip: 'Resep Tersimpan!',
    watchVideoButton: 'Tonton Video',
    generateVideoButton: 'Hasilkan Video',
    generateVideoLoading: 'Membuat video kuliner Anda. Ini mungkin memakan waktu sejenak. Silakan gulir ke bawah ke resep atau ambil segelas anggur. Kami akan menyusul Anda. Video akan terbuka di jendela baru.',
    prepTimeLabel: 'Persiapan',
    cookTimeLabel: 'Masak',
    servingsLabel: 'Porsi',
    caloriesLabel: 'Kalori',
    proteinLabel: 'Protein',
    carbsLabel: 'Karbo',
    fatLabel: 'Lemak',
    giLabel: 'IG',
    ingredientsHeader: 'Bahan-bahan',
    instructionsHeader: 'Instruksi',
    notesHeader: 'Catatan Saya',
    notesPlaceholder: 'Tambahkan catatan pribadi, penyesuaian, atau saran penyajian Anda di sini...',
    imagePlaceholder: 'Menghasilkan gambar lezat...',
    emailRecipeButton: 'Email Resep',
    emailSubjectPrefix: 'Resep',
    gmailBodyPlaceholder: 'Detail resep telah disalin ke clipboard Anda. Silakan tempel di sini (Ctrl+V atau Cmd+V).',
    recipeNotesLabel: 'Catatan resep',
    rateStarLabel: 'Beri peringkat {star} bintang',
    rateStarsLabel: 'Beri peringkat {star} bintang',
    medicalDisclaimer: 'TIDAK ADA informasi di Aplikasi ini yang dapat dianggap sebagai nasihat medis. Aplikasi ini hanya untuk tujuan hiburan. Pemilik tidak akan bertanggung jawab dengan cara apa pun.',
    downloadImageLabel: 'Unduh dan Bagikan Gambar',
    savedRecipesButton: 'Resep Tersimpan',
    savedRecipesModalTitle: 'Resep Saya yang Tersimpan',
    savedRecipesTitle: 'Resep Tersimpan',
    searchPlaceholder: 'Cari resep tersimpan...',
    noRecipesFound: 'Tidak ada resep yang cocok ditemukan.',
    noSavedRecipes: 'Anda belum menyimpan resep apa pun.',
    searchSavedRecipesLabel: 'Cari resep tersimpan',
    viewRecipeAriaLabel: 'Lihat resep untuk {recipeName}',
    deleteRecipeAriaLabel: 'Hapus resep untuk {recipeName}',
    errorOops: 'Ups!',
    errorIngredients: 'Harap masukkan beberapa bahan.',
    errorGeneration: 'Maaf, kami tidak dapat membuat resep dengan bahan-bahan tersebut. Silakan coba lagi atau sesuaikan bahan Anda.',
    errorImageGeneration: 'Maaf, kami tidak dapat membuat gambar untuk resep ini.',
    errorVideoGeneration: 'Maaf, kami tidak dapat membuat video untuk resep ini.',
    errorSocialPostGeneration: 'Maaf, kami tidak dapat membuat postingan media sosial. Silakan coba lagi.',
    initialStateTitle: 'Kreasi Kuliner Anda Menanti',
    initialStateText: 'Masukkan bahan-bahan Anda di sebelah kiri untuk memulai!',
    socialPostButton: 'Buat Postingan Sosial',
    socialModalTitle: 'Hasilkan Postingan Media Sosial',
    generateSocialPostButton: 'Hasilkan Postingan',
    generateSocialPostLoading: 'Menghasilkan...',
    copyButton: 'Salin',
    copiedButton: 'Tersalin!',
    generatedPostAriaLabel: 'Postingan media sosial yang dihasilkan',
    closeModalLabel: 'Tutup modal',
    videoModalAriaLabel: 'Video resep',
    videoNotSupported: 'Browser Anda tidak mendukung tag video.',
    closeVideoLabel: 'Tutup video',
    downloadAndShare: 'Unduh dan Bagikan',
    downloadVideoLabel: 'Unduh video',
  },
  'zh-CN': {
    headerTitle: '人工智能食谱生成器',
    footerText: '由 Gemini API 驱动。烹饪愉快！',
    selectLanguageLabel: '选择语言',
    formTitle: '你的冰箱里有什么？',
    ingredientsLabel: '列出你的食材或你想要食谱的菜名',
    ingredientsPlaceholder: '例如：鸡胸肉、西兰花、大蒜、橄榄油、柠檬',
    mealTypeLabel: '餐点类型',
    quickMealLabel: '30分钟内完成准备和烹饪',
    dietaryPreferencesLabel: '饮食偏好',
    equipmentLabel: '可用设备',
    generateButton: '生成食谱',
    generateButtonLoading: '思考中...',
    mealTypeAny: '任何',
    mealTypeBreakfast: '早餐',
    mealTypeLunch: '午餐',
    mealTypeDinner: '晚餐',
    mealTypeSnack: '小吃',
    mealTypeDessert: '甜点',
    mealTypeSoup: '汤',
    dietaryOptionVegetarian: '素食',
    dietaryOptionVegan: '纯素',
    dietaryOptionGluten_Free: '无麸质',
    dietaryOptionDairy_Free: '无乳制品',
    cookingMethodStovetop: '炉灶',
    cookingMethodOven: '烤箱',
    cookingMethodMicrowave: '微波炉',
    cookingMethodGrill: '烧烤',
    cookingMethodCharcoal_BBQ: '炭火烧烤',
    cookingMethodGas_BBQ: '燃气烧烤',
    cookingMethodAir_Fryer: '空气炸锅',
    cookingMethodNo_Cook: '免煮',
    tryAnotherButton: '换一个',
    saveButton: '保存食谱',
    savedButton: '已保存！',
    recipeSavedTooltip: '食谱已保存！',
    watchVideoButton: '观看视频',
    generateVideoButton: '生成视频',
    generateVideoLoading: '正在制作您的烹饪视频。这可能需要一些时间。请向下滚动到食谱或喝杯酒。我们会跟上您。视频将在新窗口中打开。',
    prepTimeLabel: '准备',
    cookTimeLabel: '烹饪',
    servingsLabel: '份量',
    caloriesLabel: '卡路里',
    proteinLabel: '蛋白质',
    carbsLabel: '碳水',
    fatLabel: '脂肪',
    giLabel: 'GI',
    ingredientsHeader: '食材',
    instructionsHeader: '步骤',
    notesHeader: '我的笔记',
    notesPlaceholder: '在此处添加您的个人笔记、调整或上菜建议...',
    imagePlaceholder: '正在生成美味图片...',
    emailRecipeButton: '电邮食谱',
    emailSubjectPrefix: '食谱',
    gmailBodyPlaceholder: '食谱详情已复制到剪贴板。请在此处粘贴（Ctrl+V 或 Cmd+V）。',
    recipeNotesLabel: '食谱笔记',
    rateStarLabel: '评价{star}星',
    rateStarsLabel: '评价{star}星',
    medicalDisclaimer: '本应用程序上的任何信息均不应被视为医疗建议。本应用程序仅供娱乐之用。所有者将不承担任何责任。',
    downloadImageLabel: '下载并分享图片',
    savedRecipesButton: '已存食谱',
    savedRecipesModalTitle: '我保存的食谱',
    savedRecipesTitle: '已保存的食谱',
    searchPlaceholder: '搜索已保存的食谱...',
    noRecipesFound: '未找到匹配的食谱。',
    noSavedRecipes: '您还没有保存任何食谱。',
    searchSavedRecipesLabel: '搜索已保存的食谱',
    viewRecipeAriaLabel: '查看{recipeName}的食谱',
    deleteRecipeAriaLabel: '删除{recipeName}的食谱',
    errorOops: '哎呀！',
    errorIngredients: '请输入一些食材。',
    errorGeneration: '抱歉，我们无法用这些食材生成食谱。请重试或调整您的食材。',
    errorImageGeneration: '抱歉，我们无法为此食谱创建图像。',
    errorVideoGeneration: '抱歉，我们无法为此食谱创建视频。',
    errorSocialPostGeneration: '抱歉，我们无法生成社交媒体帖子。请重试。',
    initialStateTitle: '您的烹饪创作正等待着您',
    initialStateText: '在左侧输入您的食材即可开始！',
    socialPostButton: '创建社交帖子',
    socialModalTitle: '生成社交媒体帖子',
    generateSocialPostButton: '生成帖子',
    generateSocialPostLoading: '生成中...',
    copyButton: '复制',
    copiedButton: '已复制！',
    generatedPostAriaLabel: '生成的社交媒体帖子',
    closeModalLabel: '关闭模态框',
    videoModalAriaLabel: '食谱视频',
    videoNotSupported: '您的浏览器不支持视频标签。',
    closeVideoLabel: '关闭视频',
    downloadAndShare: '下载并分享',
    downloadVideoLabel: '下载视频',
  },
  th: {
    headerTitle: 'เครื่องมือสร้างสูตรอาหาร AI',
    footerText: 'ขับเคลื่อนโดย Gemini API ขอให้สนุกกับการทำอาหาร!',
    selectLanguageLabel: 'เลือกภาษา',
    formTitle: 'ในตู้เย็นของคุณมีอะไรบ้าง?',
    ingredientsLabel: 'ใส่รายการส่วนผสมหรือชื่ออาหารที่คุณต้องการสูตร',
    ingredientsPlaceholder: 'เช่น อกไก่, บรอกโคลี, กระเทียม, น้ำมันมะกอก, มะนาว',
    mealTypeLabel: 'ประเภทอาหาร',
    quickMealLabel: 'เตรียมและปรุงอาหารในเวลาไม่เกิน 30 นาที',
    dietaryPreferencesLabel: 'ความต้องการด้านอาหาร',
    equipmentLabel: 'อุปกรณ์ที่มี',
    generateButton: 'สร้างสูตรอาหาร',
    generateButtonLoading: 'กำลังคิด...',
    mealTypeAny: 'ใดก็ได้',
    mealTypeBreakfast: 'อาหารเช้า',
    mealTypeLunch: 'อาหารกลางวัน',
    mealTypeDinner: 'อาหารเย็น',
    mealTypeSnack: 'ของว่าง',
    mealTypeDessert: 'ของหวาน',
    mealTypeSoup: 'ซุป',
    dietaryOptionVegetarian: 'มังสวิรัติ',
    dietaryOptionVegan: 'วีแกน',
    dietaryOptionGluten_Free: 'ไม่มีกลูเตน',
    dietaryOptionDairy_Free: 'ไม่มีนม',
    cookingMethodStovetop: 'เตา',
    cookingMethodOven: 'เตาอบ',
    cookingMethodMicrowave: 'ไมโครเวฟ',
    cookingMethodGrill: 'ย่าง',
    cookingMethodCharcoal_BBQ: 'เตาถ่าน',
    cookingMethodGas_BBQ: 'เตาแก๊ส',
    cookingMethodAir_Fryer: 'หม้อทอดไร้น้ำมัน',
    cookingMethodNo_Cook: 'ไม่ต้องปรุง',
    tryAnotherButton: 'ลองสูตรอื่น',
    saveButton: 'บันทึกสูตร',
    savedButton: 'บันทึกแล้ว!',
    recipeSavedTooltip: 'บันทึกสูตรแล้ว!',
    watchVideoButton: 'ดูวิดีโอ',
    generateVideoButton: 'สร้างวิดีโอ',
    generateVideoLoading: 'กำลังสร้างวิดีโอการทำอาหารของคุณ อาจใช้เวลาสักครู่ กรุณาเลื่อนลงไปที่สูตรอาหารหรือหยิบไวน์สักแก้ว เราจะตามไป วิดีโอจะเปิดขึ้นในหน้าต่างใหม่',
    prepTimeLabel: 'เตรียม',
    cookTimeLabel: 'ปรุง',
    servingsLabel: 'สำหรับ',
    caloriesLabel: 'แคลอรี่',
    proteinLabel: 'โปรตีน',
    carbsLabel: 'คาร์บ',
    fatLabel: 'ไขมัน',
    giLabel: 'GI',
    ingredientsHeader: 'ส่วนผสม',
    instructionsHeader: 'วิธีทำ',
    notesHeader: 'บันทึกของฉัน',
    notesPlaceholder: 'เพิ่มบันทึกส่วนตัว การปรับเปลี่ยน หรือข้อเสนอแนะในการเสิร์ฟที่นี่...',
    imagePlaceholder: 'กำลังสร้างภาพน่าอร่อย...',
    emailRecipeButton: 'ส่งอีเมลสูตรอาหาร',
    emailSubjectPrefix: 'สูตรอาหาร',
    gmailBodyPlaceholder: 'รายละเอียดสูตรอาหารถูกคัดลอกไปยังคลิปบอร์ดของคุณแล้ว โปรดวางที่นี่ (Ctrl+V หรือ Cmd+V)',
    recipeNotesLabel: 'บันทึกสูตร',
    rateStarLabel: 'ให้คะแนน {star} ดาว',
    rateStarsLabel: 'ให้คะแนน {star} ดาว',
    medicalDisclaimer: 'ข้อมูลใดๆ ในแอปนี้ไม่ถือเป็นคำแนะนำทางการแพทย์ แอปนี้มีไว้เพื่อความบันเทิงเท่านั้น เจ้าของจะไม่รับผิดชอบใดๆ ทั้งสิ้น',
    downloadImageLabel: 'ดาวน์โหลดและแชร์รูปภาพ',
    savedRecipesButton: 'สูตรที่บันทึกไว้',
    savedRecipesModalTitle: 'สูตรอาหารที่บันทึกไว้ของฉัน',
    savedRecipesTitle: 'สูตรที่บันทึกไว้',
    searchPlaceholder: 'ค้นหาสูตรที่บันทึกไว้...',
    noRecipesFound: 'ไม่พบสูตรที่ตรงกัน',
    noSavedRecipes: 'คุณยังไม่ได้บันทึกสูตรอาหารใดๆ',
    searchSavedRecipesLabel: 'ค้นหาสูตรที่บันทึกไว้',
    viewRecipeAriaLabel: 'ดูสูตรสำหรับ {recipeName}',
    deleteRecipeAriaLabel: 'ลบสูตรสำหรับ {recipeName}',
    errorOops: 'โอ๊ะ!',
    errorIngredients: 'กรุณาใส่ส่วนผสมบางอย่าง',
    errorGeneration: 'ขออภัย เราไม่สามารถสร้างสูตรอาหารจากส่วนผสมเหล่านี้ได้ โปรดลองอีกครั้งหรือปรับส่วนผสมของคุณ',
    errorImageGeneration: 'ขออภัย เราไม่สามารถสร้างภาพสำหรับสูตรนี้ได้',
    errorVideoGeneration: 'ขออภัย เราไม่สามารถสร้างวิดีโอสำหรับสูตรนี้ได้',
    errorSocialPostGeneration: 'ขออภัย เราไม่สามารถสร้างโพสต์โซเชียลมีเดียได้ โปรดลองอีกครั้ง',
    initialStateTitle: 'การสร้างสรรค์อาหารของคุณกำลังรออยู่',
    initialStateText: 'ป้อนส่วนผสมของคุณทางด้านซ้ายเพื่อเริ่มต้น!',
    socialPostButton: 'สร้างโพสต์โซเชียล',
    socialModalTitle: 'สร้างโพสต์โซเชียลมีเดีย',
    generateSocialPostButton: 'สร้างโพสต์',
    generateSocialPostLoading: 'กำลังสร้าง...',
    copyButton: 'คัดลอก',
    copiedButton: 'คัดลอกแล้ว!',
    generatedPostAriaLabel: 'โพสต์โซเชียลมีเดียที่สร้างขึ้น',
    closeModalLabel: 'ปิดโมดอล',
    videoModalAriaLabel: 'วิดีโอสูตรอาหาร',
    videoNotSupported: 'เบราว์เซอร์ของคุณไม่รองรับแท็กวิดีโอ',
    closeVideoLabel: 'ปิดวิดีโอ',
    downloadAndShare: 'ดาวน์โหลดและแชร์',
    downloadVideoLabel: 'ดาวน์โหลดวิดีโอ',
  },
};